#ifndef TICSQTCREATOR_GLOBAL_H
#define TICSQTCREATOR_GLOBAL_H

#include <QtGlobal>

#if defined(TICSQTCREATOR_LIBRARY)
#  define TICSQTCREATORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TICSQTCREATORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TICSQTCREATOR_GLOBAL_H
